// <auto-generated />
using System;
using CaixaProjeto.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaixaProjeto.ApiService.Data.Migrations
{
    [DbContext(typeof(CaixaDbContext))]
    partial class CaixaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nif")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.HistoricoEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoNovo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Utilizador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("HistoricoEstados");
                });

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.MotivoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Decisao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Regra")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("MotivosPedido");
                });

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSubmissao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisaoAutomatica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoAtual")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("IdadeFinalContrato")
                        .HasColumnType("REAL");

                    b.Property<bool>("IncidentesCredito")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LimiteMontante")
                        .HasColumnType("REAL");

                    b.Property<string>("Nif")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PrestacaoEstimada")
                        .HasColumnType("REAL");

                    b.Property<double>("PrestacoesAtuais")
                        .HasColumnType("REAL");

                    b.Property<double>("RendimentoMensalLiquido")
                        .HasColumnType("REAL");

                    b.Property<string>("SituacaoProfissional")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TaxaEsforco")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorPretendido")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataSubmissao");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decisao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncidentesCredito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nif")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrestacoesAtuais")
                        .HasColumnType("REAL");

                    b.Property<double>("RendimentoMensalLiquido")
                        .HasColumnType("REAL");

                    b.Property<string>("SituacaoProfissional")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorPretendido")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataSimulacao");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.HistoricoEstado", b =>
                {
                    b.HasOne("CaixaProjeto.ApiService.Data.Pedido", null)
                        .WithMany("Historico")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.MotivoPedido", b =>
                {
                    b.HasOne("CaixaProjeto.ApiService.Data.Pedido", null)
                        .WithMany("Motivos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.Pedido", b =>
                {
                    b.HasOne("CaixaProjeto.ApiService.Data.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.Simulacao", b =>
                {
                    b.HasOne("CaixaProjeto.ApiService.Data.Cliente", "Cliente")
                        .WithMany("Simulacoes")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.Cliente", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Simulacoes");
                });

            modelBuilder.Entity("CaixaProjeto.ApiService.Data.Pedido", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("Motivos");
                });
#pragma warning restore 612, 618
        }
    }
}
