@ApiService_HostAddress = http://localhost:5509

GET {{ApiService_HostAddress}}/
Accept: text/plain

###

# Cenário B do enunciado: espera-se ANÁLISE MANUAL
POST {{ApiService_HostAddress}}/api/pedidos/preanalise
Content-Type: application/json

{
  "nif": "123456789",
  "idade": 42,
  "rendimentoMensalLiquido": 2000,
  "prestacoesAtuais": 500,
  "valorPretendido": 20000,
  "prazoMeses": 48,
  "situacaoProfissional": "ContratoPrazo",
  "incidentesCredito": false
}

###

# Lista de pedidos gravados: só os que estão em análise manual, primeira página
GET {{ApiService_HostAddress}}/api/pedidos?estado=AnaliseManual&pagina=1&tamanho=20
Accept: application/json

###
