<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaixaProjeto.ServiceDefaults\CaixaProjeto.ServiceDefaults.csproj" />
    <ProjectReference Include="..\CaixaProjeto.Core\CaixaProjeto.Core.csproj" />
  </ItemGroup>

</Project>
